demo_logging_server/config/routes.rb
DemoLoggingServer::Application.routes.draw do
  resources :exception_logs

end

demo_logging_server/app/models/exception_log.rb
class ExceptionLog < ActiveRecord::Base
  attr_accessible :Message, :Parameters, :URL, :backtrace, :count, :time_stamp
end

demo_logging_server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

demo_logging_server/app/controllers/exception_logs_controller.rb
class ExceptionLogsController < ApplicationController
  # GET /exception_logs
  # GET /exception_logs.json
  def index
    @exception_logs = ExceptionLog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exception_logs }
    end
  end

  # GET /exception_logs/1
  # GET /exception_logs/1.json
  def show
    @exception_log = ExceptionLog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exception_log }
    end
  end

  # GET /exception_logs/new
  # GET /exception_logs/new.json
  def new
    @exception_log = ExceptionLog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exception_log }
    end
  end

  # GET /exception_logs/1/edit
  def edit
    @exception_log = ExceptionLog.find(params[:id])
  end

  # POST /exception_logs
  # POST /exception_logs.json
  def create
    @exception_log = ExceptionLog.new(params[:exception_log])

    respond_to do |format|
      if @exception_log.save
        format.html { redirect_to @exception_log, notice: 'Exception log was successfully created.' }
        format.json { render json: @exception_log, status: :created, location: @exception_log }
      else
        format.html { render action: "new" }
        format.json { render json: @exception_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exception_logs/1
  # PUT /exception_logs/1.json
  def update
    @exception_log = ExceptionLog.find(params[:id])

    respond_to do |format|
      if @exception_log.update_attributes(params[:exception_log])
        format.html { redirect_to @exception_log, notice: 'Exception log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exception_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exception_logs/1
  # DELETE /exception_logs/1.json
  def destroy
    @exception_log = ExceptionLog.find(params[:id])
    @exception_log.destroy

    respond_to do |format|
      format.html { redirect_to exception_logs_url }
      format.json { head :no_content }
    end
  end
end

demo_logging_server/app/helpers/application_helper.rb
module ApplicationHelper
end

demo_logging_server/app/helpers/exception_logs_helper.rb
module ExceptionLogsHelper
end

demo_logging_server/app/views/exception_logs/_form.html.erb
<%= form_for(@exception_log) do |f| %>
  <% if @exception_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exception_log.errors.count, "error") %> prohibited this exception_log from being saved:</h2>

      <ul>
      <% @exception_log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :URL %><br />
    <%= f.text_field :URL %>
  </div>
  <div class="field">
    <%= f.label :Message %><br />
    <%= f.text_field :Message %>
  </div>
  <div class="field">
    <%= f.label :Parameters %><br />
    <%= f.text_field :Parameters %>
  </div>
  <div class="field">
    <%= f.label :backtrace %><br />
    <%= f.text_field :backtrace %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.number_field :count %>
  </div>
  <div class="field">
    <%= f.label :time_stamp %><br />
    <%= f.datetime_select :time_stamp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

demo_logging_server/app/views/exception_logs/edit.html.erb
<h1>Editing exception_log</h1>

<%= render 'form' %>

<%= link_to 'Show', @exception_log %> |
<%= link_to 'Back', exception_logs_path %>

demo_logging_server/app/views/exception_logs/index.html.erb
<h1>Listing exception_logs</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Message</th>
    <th>Parameters</th>
    <th>Backtrace</th>
    <th>Count</th>
    <th>Time stamp</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exception_logs.each do |exception_log| %>
  <tr>
    <td><%= exception_log.URL %></td>
    <td><%= exception_log.Message %></td>
    <td><%= exception_log.Parameters %></td>
    <td><%= exception_log.backtrace %></td>
    <td><%= exception_log.count %></td>
    <td><%= exception_log.time_stamp %></td>
    <td><%= link_to 'Show', exception_log %></td>
    <td><%= link_to 'Edit', edit_exception_log_path(exception_log) %></td>
    <td><%= link_to 'Destroy', exception_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Exception log', new_exception_log_path %>

demo_logging_server/app/views/exception_logs/new.html.erb
<h1>New exception_log</h1>

<%= render 'form' %>

<%= link_to 'Back', exception_logs_path %>

demo_logging_server/app/views/exception_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @exception_log.URL %>
</p>

<p>
  <b>Message:</b>
  <%= @exception_log.Message %>
</p>

<p>
  <b>Parameters:</b>
  <%= @exception_log.Parameters %>
</p>

<p>
  <b>Backtrace:</b>
  <%= @exception_log.backtrace %>
</p>

<p>
  <b>Count:</b>
  <%= @exception_log.count %>
</p>

<p>
  <b>Time stamp:</b>
  <%= @exception_log.time_stamp %>
</p>


<%= link_to 'Edit', edit_exception_log_path(@exception_log) %> |
<%= link_to 'Back', exception_logs_path %>

demo_logging_server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoLoggingServer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>